title: Blog do Joel
email: joelcsilva@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog criado com o objetivo de ampliar os meus conhecimentos e criar uns tutoriais.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jhoow13z
github_username:  jhoow13

# Build settings
markdown: kramdown
permalink: /:title
theme: minima
plugins:
  - jekyll-feed

exclude: ['package.json', 'node_modules', 'gulpfile.js']